### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by ghost** [SaschaLK/Soundglider#15]
Was meinst du wie wir das Canvas ( der Teil auf dem gezeichnet wird) impelemntieren sollen:
Soll ich das mit Javascript erstellen oder willst du das über Html einbinden?

**Comment by SaschaLK** [comment]
Also ich denke wir sollten das mithilfe von Javascript machen. Also das Spiel an sich sollte denke ich nur in einer Sprache verfasst werden um irgendwelche seltsamen codeinteraktionen zu vermeiden.
